root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/code_scout"
  cmd = "make notify-templ-proxy && npx tailwindcss -o ./view/static/css/tailwind.css --minify && go build -tags local -o ./bin/code_scout ./main.go"
  delay = 1000 # Lowered from 10000 for faster hot-reloads
  exclude_dir = ["tmp", "bin", "node_modules", ".git"]
  exclude_regex = [".*\\.txt$"]
  include_ext = ["go", "html", "css", "templ"]
  log = "build-errors.log"
  rerun_delay = 500
  send_interrupt = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[screen]
  keep_scroll = true
