package error_codes

const (
	// Origin Prefixes
	PREFIX_MULTIPLIER_ERR_CODE = 1000000

	CODE_SCOUT_SERVICE_PREFIX_ERR_CODE = 47 * PREFIX_MULTIPLIER_ERR_CODE

	AUTHORIZATION_HEADER_MISSING  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10000
	UNAUTHORIZED                  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10001
	INVALID_REQUEST_DATA_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10002

	ERR_INVALID_PROJECT_NAME_ERR_CODE      = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20000
	ERR_FAILED_TO_CREATE_PROJECT_ERR_CODE  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20001
	ERR_FAILED_TO_DELETE_PROJECT_ERR_CODE  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20002
	PROJECT_ID_HEADER_MISSING_ERR_CODE     = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20003
	PROJECT_SECRET_HEADER_MISSING_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20004
	INVALID_PROJECT_ID_HEADER_ERR_CODE     = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20005
	INVALID_PROJECT_SECRET_HEADER_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20006
)
