package error_codes

const (
	// Origin Prefixes
	PREFIX_MULTIPLIER_ERR_CODE = 1000000

	HAI_CODE_SCOUT_SERVICE_PREFIX_ERR_CODE = 47 * PREFIX_MULTIPLIER_ERR_CODE

	AUTHORIZATION_HEADER_MISSING = HAI_CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10000
	UNAUTHORIZED                 = HAI_CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10001
)
