package domain

import "errors"

// ErrNotFound lets services branch on "the row is not there" without importing
// gorm. Repositories translate gorm.ErrRecordNotFound into this.
var ErrNotFound = errors.New("not found")

const (
	// Origin Prefixes
	PREFIX_MULTIPLIER_ERR_CODE = 1000000

	CODE_SCOUT_SERVICE_PREFIX_ERR_CODE = 47 * PREFIX_MULTIPLIER_ERR_CODE

	// Error Codes
	AUTHORIZATION_HEADER_MISSING  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10000
	UNAUTHORIZED                  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10001
	INVALID_REQUEST_DATA_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10002
	// Its own code, not INVALID_REQUEST_DATA: an SDK must be able to tell
	// "your batch is too big, send fewer" apart from "your payload is
	// malformed", because only one of those is fixable by trying differently.
	ERR_PAYLOAD_TOO_LARGE_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 10003

	ERR_INVALID_PROJECT_NAME_ERR_CODE      = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20000
	ERR_FAILED_TO_CREATE_PROJECT_ERR_CODE  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20001
	ERR_FAILED_TO_DELETE_PROJECT_ERR_CODE  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20002
	PROJECT_ID_HEADER_MISSING_ERR_CODE     = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20003
	PROJECT_SECRET_HEADER_MISSING_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20004
	INVALID_PROJECT_ID_HEADER_ERR_CODE     = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20005
	INVALID_PROJECT_SECRET_HEADER_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20006
	ERR_PROJECT_NOT_FOUND_ERR_CODE         = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20007
	ERR_FAILED_TO_UPDATE_PROJECT_ERR_CODE  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20008
	ERR_FAILED_TO_ROTATE_SECRET_ERR_CODE   = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20009
	ERR_PROJECT_SECRET_MISSING_ERR_CODE    = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20010
	ERR_INVALID_INSTANCE_SETTING_ERR_CODE  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 20011

	// Auth error codes
	ERR_INVALID_EMAIL_ERR_CODE       = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 30000
	ERR_INVALID_PASSWORD_ERR_CODE    = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 30001
	ERR_USER_ALREADY_EXISTS_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 30002
	ERR_INVALID_CREDENTIALS_ERR_CODE = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 30003
	ERR_SESSION_NOT_FOUND_ERR_CODE   = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 30004
	ERR_PASSWORDS_DO_NOT_MATCH_CODE  = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 30005
	ERR_SESSION_EXPIRED_ERR_CODE     = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 30006
	ERR_INVALID_NAME_ERR_CODE        = CODE_SCOUT_SERVICE_PREFIX_ERR_CODE + 30007

	// Error Messages
	ERR_PAYLOAD_TOO_LARGE_ERR = "Upload is larger than this instance allows"

	AUTHORIZATION_HEADER_MISSING_ERR = "Missing Authorization header"
	UNAUTHORIZED_ERR                 = "Unauthorized"
	INVALID_REQUEST_DATA_ERR         = "Invalid request data"

	ERR_INVALID_PROJECT_NAME_ERR      = "Project name cannot be empty"
	ERR_FAILED_TO_CREATE_PROJECT_ERR  = "Failed to create project"
	ERR_FAILED_TO_DELETE_PROJECT_ERR  = "Failed to delete project"
	PROJECT_ID_HEADER_MISSING_ERR     = "Missing Project ID header"
	PROJECT_SECRET_HEADER_MISSING_ERR = "Missing Project Secret header"
	INVALID_PROJECT_ID_HEADER_ERR     = "Invalid Project ID header"
	INVALID_PROJECT_SECRET_HEADER_ERR = "Invalid Project Secret header"
	ERR_PROJECT_NOT_FOUND_ERR         = "Project not found"
	ERR_FAILED_TO_UPDATE_PROJECT_ERR  = "Failed to update project"
	ERR_FAILED_TO_ROTATE_SECRET_ERR   = "Failed to rotate the secret key"
	ERR_PROJECT_SECRET_MISSING_ERR    = "This project has no secret key"
	ERR_INVALID_INSTANCE_SETTING_ERR  = "Invalid instance setting"

	// Auth error messages
	ERR_INVALID_EMAIL_ERR       = "Enter a valid email address"
	ERR_INVALID_NAME_ERR        = "Name cannot be empty"
	ERR_INVALID_PASSWORD_ERR    = "Password must be at least 6 characters"
	ERR_USER_ALREADY_EXISTS_ERR = "An account with that email already exists"
	ERR_INVALID_CREDENTIALS_ERR = "Invalid email or password"
	ERR_SESSION_NOT_FOUND_ERR   = "Session not found or expired"
	ERR_PASSWORDS_DO_NOT_MATCH  = "Passwords do not match"
	ERR_SESSION_EXPIRED_ERR     = "Session has expired"
)
